name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: 📚 Checkout
        uses: actions/checkout@v4

      - name: 🏗 Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🧪 Run tests
        run: npm run test:ci

      - name: 🔍 ESLint
        run: npm run lint

      - name: 💅 Prettier check
        run: npm run format:check

      - name: 📝 Markdown lint
        run: npm run lint:md

      - name: 🏗 TypeScript check
        run: npm run type-check

      - name: 📱 Expo check
        run: npx expo install --check

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: 📚 Checkout
        uses: actions/checkout@v4

      - name: 🏗 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🏗 Build for web
        run: npx expo export --platform web
